services:
  db:
    image: "postgres:latest"
    restart: always
    container_name: postgres_fastapi
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - fastapi_network

  backend:
    restart: always
    build: .
    container_name: backend_fastapi
    command: ["/entrypoint.sh"]
    environment:
      - WATCHFILES_FORCE_POLLING=true
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - fastapi_network

  migrator:
    build: .
    container_name: alembic_migrator
    command: /migration_script.sh
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
