services:
  db:
    image: "postgres:latest"
    restart: always
    container_name: postgres_fastapi
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network

  backend:
    restart: always
    build: .
    container_name: backend_fastapi
    command: ["/entrypoint.sh"]
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge

volumes:
  postgres_data:
